services:
  - type: web
    name: minio-server
    runtime: docker
    repo: https://github.com/zapintix/Minio2
    branch: main
    dockerfilePath: Dockerfile
    envVars:
      - key: MINIO_ROOT_USER
        value: admin
      - key: MINIO_ROOT_PASSWORD
        value: password
      - key: PORT
        value: "9000"
      - key: CONSOLE_PORT
        value: "9001"
    plan: free
    autoDeploy: true
    healthCheckPath: /minio/health/live
