services:
  - type: service
    name: minio-server
    env: docker
    repo: https://github.com/zapintix/Minio2
    branch: main
    dockerfilePath: Dockerfile
    envVars:
      - key: MINIO_ROOT_USER
        value: admin
      - key: MINIO_ROOT_PASSWORD
        value: password
    plan: free
    autoDeploy: true
    healthCheckPath: /minio/health/live
    ports:
      - port: 9000
      - port: 9001
