services:
- type: web
  name: minio-server
  runtime: image
  image:
    url: docker.io/minio/minio:latest
  dockerCommand: minio server /data
  autoDeploy: false
  disk:
    name: data
    mountPath: /data
